# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Runtime:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RuntimeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Runtime.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RUNTIME_UNSPECIFIED: _Runtime.ValueType  # 0
    RUNTIME_TFLITE: _Runtime.ValueType  # 1
    RUNTIME_QNN_DLC: _Runtime.ValueType  # 2
    RUNTIME_QNN_CONTEXT_BINARY: _Runtime.ValueType  # 3
    RUNTIME_ONNX: _Runtime.ValueType  # 4
    RUNTIME_PRECOMPILED_QNN_ONNX: _Runtime.ValueType  # 5
    RUNTIME_GENIE: _Runtime.ValueType  # 6
    RUNTIME_VOICE_AI: _Runtime.ValueType  # 7
    RUNTIME_GENIEX_QAIRT: _Runtime.ValueType  # 11

class Runtime(_Runtime, metaclass=_RuntimeEnumTypeWrapper): ...

RUNTIME_UNSPECIFIED: Runtime.ValueType  # 0
RUNTIME_TFLITE: Runtime.ValueType  # 1
RUNTIME_QNN_DLC: Runtime.ValueType  # 2
RUNTIME_QNN_CONTEXT_BINARY: Runtime.ValueType  # 3
RUNTIME_ONNX: Runtime.ValueType  # 4
RUNTIME_PRECOMPILED_QNN_ONNX: Runtime.ValueType  # 5
RUNTIME_GENIE: Runtime.ValueType  # 6
RUNTIME_VOICE_AI: Runtime.ValueType  # 7
RUNTIME_GENIEX_QAIRT: Runtime.ValueType  # 11
global___Runtime = Runtime
