# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import shared.runtime_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _FormFactor:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FormFactorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FormFactor.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FORM_FACTOR_UNSPECIFIED: _FormFactor.ValueType  # 0
    FORM_FACTOR_PHONE: _FormFactor.ValueType  # 1
    FORM_FACTOR_TABLET: _FormFactor.ValueType  # 2
    FORM_FACTOR_AUTO: _FormFactor.ValueType  # 3
    FORM_FACTOR_XR: _FormFactor.ValueType  # 4
    FORM_FACTOR_COMPUTE: _FormFactor.ValueType  # 5
    FORM_FACTOR_IOT: _FormFactor.ValueType  # 6

class FormFactor(_FormFactor, metaclass=_FormFactorEnumTypeWrapper):
    """---------------------------------------------------------------------------
    Enums & Descriptor Structs
    ---------------------------------------------------------------------------
    """

FORM_FACTOR_UNSPECIFIED: FormFactor.ValueType  # 0
FORM_FACTOR_PHONE: FormFactor.ValueType  # 1
FORM_FACTOR_TABLET: FormFactor.ValueType  # 2
FORM_FACTOR_AUTO: FormFactor.ValueType  # 3
FORM_FACTOR_XR: FormFactor.ValueType  # 4
FORM_FACTOR_COMPUTE: FormFactor.ValueType  # 5
FORM_FACTOR_IOT: FormFactor.ValueType  # 6
global___FormFactor = FormFactor

class _OperatingSystemType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperatingSystemTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OperatingSystemType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPERATING_SYSTEM_TYPE_UNSPECIFIED: _OperatingSystemType.ValueType  # 0
    OPERATING_SYSTEM_TYPE_ANDROID: _OperatingSystemType.ValueType  # 1
    OPERATING_SYSTEM_TYPE_WINDOWS: _OperatingSystemType.ValueType  # 2
    OPERATING_SYSTEM_TYPE_LINUX: _OperatingSystemType.ValueType  # 3
    OPERATING_SYSTEM_TYPE_QC_LINUX: _OperatingSystemType.ValueType  # 4

class OperatingSystemType(_OperatingSystemType, metaclass=_OperatingSystemTypeEnumTypeWrapper): ...

OPERATING_SYSTEM_TYPE_UNSPECIFIED: OperatingSystemType.ValueType  # 0
OPERATING_SYSTEM_TYPE_ANDROID: OperatingSystemType.ValueType  # 1
OPERATING_SYSTEM_TYPE_WINDOWS: OperatingSystemType.ValueType  # 2
OPERATING_SYSTEM_TYPE_LINUX: OperatingSystemType.ValueType  # 3
OPERATING_SYSTEM_TYPE_QC_LINUX: OperatingSystemType.ValueType  # 4
global___OperatingSystemType = OperatingSystemType

class _WebsiteWorld:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WebsiteWorldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WebsiteWorld.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WEBSITE_WORLD_UNSPECIFIED: _WebsiteWorld.ValueType  # 0
    WEBSITE_WORLD_MOBILE: _WebsiteWorld.ValueType  # 1
    WEBSITE_WORLD_COMPUTE: _WebsiteWorld.ValueType  # 2
    WEBSITE_WORLD_AUTOMOTIVE: _WebsiteWorld.ValueType  # 3
    WEBSITE_WORLD_IOT: _WebsiteWorld.ValueType  # 4
    WEBSITE_WORLD_XR: _WebsiteWorld.ValueType  # 5

class WebsiteWorld(_WebsiteWorld, metaclass=_WebsiteWorldEnumTypeWrapper): ...

WEBSITE_WORLD_UNSPECIFIED: WebsiteWorld.ValueType  # 0
WEBSITE_WORLD_MOBILE: WebsiteWorld.ValueType  # 1
WEBSITE_WORLD_COMPUTE: WebsiteWorld.ValueType  # 2
WEBSITE_WORLD_AUTOMOTIVE: WebsiteWorld.ValueType  # 3
WEBSITE_WORLD_IOT: WebsiteWorld.ValueType  # 4
WEBSITE_WORLD_XR: WebsiteWorld.ValueType  # 5
global___WebsiteWorld = WebsiteWorld

class _WebsiteIcon:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WebsiteIconEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WebsiteIcon.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WEBSITE_ICON_UNSPECIFIED: _WebsiteIcon.ValueType  # 0
    WEBSITE_ICON_CAR: _WebsiteIcon.ValueType  # 1
    WEBSITE_ICON_IOT_CHIP: _WebsiteIcon.ValueType  # 2
    WEBSITE_ICON_IOT_DRONE: _WebsiteIcon.ValueType  # 3
    WEBSITE_ICON_LAPTOP_GENERIC: _WebsiteIcon.ValueType  # 4
    WEBSITE_ICON_LAPTOP_X_ELITE: _WebsiteIcon.ValueType  # 5
    WEBSITE_ICON_PHONE_S21: _WebsiteIcon.ValueType  # 6
    WEBSITE_ICON_PHONE_S22: _WebsiteIcon.ValueType  # 7
    WEBSITE_ICON_PHONE_S23: _WebsiteIcon.ValueType  # 8
    WEBSITE_ICON_PHONE_S23_ULTRA: _WebsiteIcon.ValueType  # 9
    WEBSITE_ICON_PHONE_S24: _WebsiteIcon.ValueType  # 10
    WEBSITE_ICON_PHONE_S24_ULTRA: _WebsiteIcon.ValueType  # 11
    WEBSITE_ICON_TABLET_ANDROID: _WebsiteIcon.ValueType  # 12
    WEBSITE_ICON_XR_HEADSET: _WebsiteIcon.ValueType  # 13

class WebsiteIcon(_WebsiteIcon, metaclass=_WebsiteIconEnumTypeWrapper): ...

WEBSITE_ICON_UNSPECIFIED: WebsiteIcon.ValueType  # 0
WEBSITE_ICON_CAR: WebsiteIcon.ValueType  # 1
WEBSITE_ICON_IOT_CHIP: WebsiteIcon.ValueType  # 2
WEBSITE_ICON_IOT_DRONE: WebsiteIcon.ValueType  # 3
WEBSITE_ICON_LAPTOP_GENERIC: WebsiteIcon.ValueType  # 4
WEBSITE_ICON_LAPTOP_X_ELITE: WebsiteIcon.ValueType  # 5
WEBSITE_ICON_PHONE_S21: WebsiteIcon.ValueType  # 6
WEBSITE_ICON_PHONE_S22: WebsiteIcon.ValueType  # 7
WEBSITE_ICON_PHONE_S23: WebsiteIcon.ValueType  # 8
WEBSITE_ICON_PHONE_S23_ULTRA: WebsiteIcon.ValueType  # 9
WEBSITE_ICON_PHONE_S24: WebsiteIcon.ValueType  # 10
WEBSITE_ICON_PHONE_S24_ULTRA: WebsiteIcon.ValueType  # 11
WEBSITE_ICON_TABLET_ANDROID: WebsiteIcon.ValueType  # 12
WEBSITE_ICON_XR_HEADSET: WebsiteIcon.ValueType  # 13
global___WebsiteIcon = WebsiteIcon

@typing.final
class OperatingSystem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OSTYPE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    ostype: global___OperatingSystemType.ValueType
    version: builtins.str
    def __init__(
        self,
        *,
        ostype: global___OperatingSystemType.ValueType = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ostype", b"ostype", "version", b"version"]) -> None: ...

global___OperatingSystem = OperatingSystem

@typing.final
class FormFactorInfo(google.protobuf.message.Message):
    """---------------------------------------------------------------------------
    Metadata Structs
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FORM_FACTOR_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    WORLD_FIELD_NUMBER: builtins.int
    form_factor: global___FormFactor.ValueType
    display_name: builtins.str
    world: global___WebsiteWorld.ValueType
    def __init__(
        self,
        *,
        form_factor: global___FormFactor.ValueType = ...,
        display_name: builtins.str = ...,
        world: global___WebsiteWorld.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["display_name", b"display_name", "form_factor", b"form_factor", "world", b"world"]) -> None: ...

global___FormFactorInfo = FormFactorInfo

@typing.final
class DeviceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CHIPSET_FIELD_NUMBER: builtins.int
    NPU_COUNT_FIELD_NUMBER: builtins.int
    OS_FIELD_NUMBER: builtins.int
    FORM_FACTOR_FIELD_NUMBER: builtins.int
    VENDOR_FIELD_NUMBER: builtins.int
    ICON_FIELD_NUMBER: builtins.int
    ENABLED_IN_SCORECARD_FIELD_NUMBER: builtins.int
    AVAILABLE_IN_WORKBENCH_FIELD_NUMBER: builtins.int
    REFERENCE_CHIPSET_FIELD_NUMBER: builtins.int
    name: builtins.str
    chipset: builtins.str
    npu_count: builtins.int
    form_factor: global___FormFactor.ValueType
    vendor: builtins.str
    icon: global___WebsiteIcon.ValueType
    enabled_in_scorecard: builtins.bool
    available_in_workbench: builtins.bool
    reference_chipset: builtins.str
    """For "similar" devices not in workbench: the chipset whose perf numbers
    are duplicated onto this device. Empty for workbench-native devices.
    """
    @property
    def os(self) -> global___OperatingSystem: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        chipset: builtins.str = ...,
        npu_count: builtins.int = ...,
        os: global___OperatingSystem | None = ...,
        form_factor: global___FormFactor.ValueType = ...,
        vendor: builtins.str = ...,
        icon: global___WebsiteIcon.ValueType = ...,
        enabled_in_scorecard: builtins.bool = ...,
        available_in_workbench: builtins.bool = ...,
        reference_chipset: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["os", b"os"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["available_in_workbench", b"available_in_workbench", "chipset", b"chipset", "enabled_in_scorecard", b"enabled_in_scorecard", "form_factor", b"form_factor", "icon", b"icon", "name", b"name", "npu_count", b"npu_count", "os", b"os", "reference_chipset", b"reference_chipset", "vendor", b"vendor"]) -> None: ...

global___DeviceInfo = DeviceInfo

@typing.final
class ChipsetInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ALIASES_FIELD_NUMBER: builtins.int
    MARKETING_NAME_FIELD_NUMBER: builtins.int
    WORLD_FIELD_NUMBER: builtins.int
    SUPPORTS_FP16_FIELD_NUMBER: builtins.int
    HTP_VERSION_FIELD_NUMBER: builtins.int
    SOC_MODEL_FIELD_NUMBER: builtins.int
    REFERENCE_DEVICE_FIELD_NUMBER: builtins.int
    SUPPORTS_WEIGHT_SHARING_FIELD_NUMBER: builtins.int
    name: builtins.str
    marketing_name: builtins.str
    world: global___WebsiteWorld.ValueType
    supports_fp16: builtins.bool
    htp_version: builtins.int
    soc_model: builtins.int
    reference_device: builtins.str
    supports_weight_sharing: builtins.bool
    @property
    def aliases(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        aliases: collections.abc.Iterable[builtins.str] | None = ...,
        marketing_name: builtins.str = ...,
        world: global___WebsiteWorld.ValueType = ...,
        supports_fp16: builtins.bool = ...,
        htp_version: builtins.int = ...,
        soc_model: builtins.int = ...,
        reference_device: builtins.str = ...,
        supports_weight_sharing: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aliases", b"aliases", "htp_version", b"htp_version", "marketing_name", b"marketing_name", "name", b"name", "reference_device", b"reference_device", "soc_model", b"soc_model", "supports_fp16", b"supports_fp16", "supports_weight_sharing", b"supports_weight_sharing", "world", b"world"]) -> None: ...

global___ChipsetInfo = ChipsetInfo

@typing.final
class RuntimeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUNTIME_FIELD_NUMBER: builtins.int
    WEBSITE_RUNTIME_FIELD_NUMBER: builtins.int
    FILE_EXTENSION_FIELD_NUMBER: builtins.int
    IS_AOT_COMPILED_FIELD_NUMBER: builtins.int
    runtime: shared.runtime_pb2.Runtime.ValueType
    website_runtime: builtins.str
    file_extension: builtins.str
    is_aot_compiled: builtins.bool
    def __init__(
        self,
        *,
        runtime: shared.runtime_pb2.Runtime.ValueType = ...,
        website_runtime: builtins.str = ...,
        file_extension: builtins.str = ...,
        is_aot_compiled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_extension", b"file_extension", "is_aot_compiled", b"is_aot_compiled", "runtime", b"runtime", "website_runtime", b"website_runtime"]) -> None: ...

global___RuntimeInfo = RuntimeInfo

@typing.final
class PlatformInfo(google.protobuf.message.Message):
    """AI Hub Platform registry: devices, chipsets, form factors, and runtimes."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AIHM_VERSION_FIELD_NUMBER: builtins.int
    RUNTIMES_FIELD_NUMBER: builtins.int
    FORM_FACTORS_FIELD_NUMBER: builtins.int
    DEVICES_FIELD_NUMBER: builtins.int
    CHIPSETS_FIELD_NUMBER: builtins.int
    aihm_version: builtins.str
    @property
    def runtimes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RuntimeInfo]: ...
    @property
    def form_factors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FormFactorInfo]: ...
    @property
    def devices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceInfo]: ...
    @property
    def chipsets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ChipsetInfo]: ...
    def __init__(
        self,
        *,
        aihm_version: builtins.str = ...,
        runtimes: collections.abc.Iterable[global___RuntimeInfo] | None = ...,
        form_factors: collections.abc.Iterable[global___FormFactorInfo] | None = ...,
        devices: collections.abc.Iterable[global___DeviceInfo] | None = ...,
        chipsets: collections.abc.Iterable[global___ChipsetInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aihm_version", b"aihm_version", "chipsets", b"chipsets", "devices", b"devices", "form_factors", b"form_factors", "runtimes", b"runtimes"]) -> None: ...

global___PlatformInfo = PlatformInfo
